#!/bin/bash
count=0
for i in {1..5}
do
    sleep 10 &
done
for i in {1..5}
do
    dd if=/dev/zero of=/dev/null &
done
wait
count=$(ps -ef | grep -c "sleep\|dd")
echo $count > processed_processes.txt
sleep 3600


#!/bin/bash
for i in {1..3}
do
    pkill sleep
    pkill dd
done


#!/bin/bash
pkill script1.sh

git commit -am "Adding a random commit to main branch"
git checkout dev/task4
git rebase main
git checkout main
git merge dev/task4
